version: '3.8'

services:
  api:
    build: .
    container_name: ytjf-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ${MEDIA_PATH:-/volume1/media}:/media
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - DOWNLOAD_DIR=/downloads
      - MEDIA_DIR=/media
      - CONFIG_DIR=/config
      - COMPLETED_DIR=/media/completed
      - MAX_CONCURRENT_DOWNLOADS=2
      - TRANSCODE_THREADS=4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 